// Word data for the English learning app, grouped by category.
// "word" and "example" stay in English (the language being taught);
// "translation" is the Hebrew word/phrase the learner is matching it to.
const WORD_DATA = {
  basics: [
    { word: "Hello", translation: "שלום", example: "Hello, how are you today?" },
    { word: "Goodbye", translation: "להתראות", example: "She waved and said goodbye." },
    { word: "Please", translation: "בבקשה", example: "Could you pass the salt, please?" },
    { word: "Thanks", translation: "תודה", example: "Thanks for helping me move." },
    { word: "Sorry", translation: "סליחה", example: "I'm sorry I was late." },
    { word: "Yes", translation: "כן", example: "Yes, I would love to come." },
    { word: "No", translation: "לא", example: "No, I haven't seen it." },
    { word: "Friend", translation: "חבר", example: "He is my best friend." },
    { word: "Family", translation: "משפחה", example: "We are having a family dinner tonight." },
    { word: "Home", translation: "בית", example: "I can't wait to get home." }
  ],
  food: [
    { word: "Apple", translation: "תפוח", example: "She ate an apple for breakfast." },
    { word: "Bread", translation: "לחם", example: "He bought a loaf of bread." },
    { word: "Water", translation: "מים", example: "Please drink more water." },
    { word: "Restaurant", translation: "מסעדה", example: "We ate at a nice restaurant." },
    { word: "Delicious", translation: "טעים", example: "This soup is delicious." },
    { word: "Hungry", translation: "רעב", example: "I'm so hungry, let's eat now." },
    { word: "Recipe", translation: "מתכון", example: "She followed the recipe carefully." },
    { word: "Breakfast", translation: "ארוחת בוקר", example: "We had eggs for breakfast." },
    { word: "Vegetable", translation: "ירק", example: "He grows vegetables in his garden." },
    { word: "Dessert", translation: "קינוח", example: "Ice cream is my favorite dessert." }
  ],
  travel: [
    { word: "Airport", translation: "שדה תעופה", example: "We arrived at the airport early." },
    { word: "Passport", translation: "דרכון", example: "Don't forget your passport." },
    { word: "Luggage", translation: "כבודה", example: "She checked her luggage at the counter." },
    { word: "Ticket", translation: "כרטיס", example: "He bought a train ticket." },
    { word: "Journey", translation: "מסע", example: "It was a long journey by bus." },
    { word: "Hotel", translation: "מלון", example: "We stayed at a hotel near the beach." },
    { word: "Map", translation: "מפה", example: "Use the map to find your way." },
    { word: "Suitcase", translation: "מזוודה", example: "He packed his suitcase for the trip." },
    { word: "Destination", translation: "יעד", example: "Our final destination was Rome." },
    { word: "Explore", translation: "לחקור", example: "They love to explore new cities." }
  ],
  business: [
    { word: "Meeting", translation: "פגישה", example: "We have a meeting at 10 AM." },
    { word: "Deadline", translation: "מועד אחרון", example: "The deadline for the report is Friday." },
    { word: "Colleague", translation: "עמית", example: "My colleague helped me finish the project." },
    { word: "Salary", translation: "משכורת", example: "She negotiated a higher salary." },
    { word: "Contract", translation: "חוזה", example: "They signed the contract yesterday." },
    { word: "Manager", translation: "מנהל", example: "The manager approved my request." },
    { word: "Client", translation: "לקוח", example: "We met with an important client today." },
    { word: "Budget", translation: "תקציב", example: "The project stayed within budget." },
    { word: "Schedule", translation: "לוח זמנים", example: "Check the schedule before you leave." },
    { word: "Negotiate", translation: "לנהל משא ומתן", example: "They negotiated a better price." }
  ],
  foundation: [
  { word: "a/an", translation: "אחד/אחת", example: "I have an apple in my bag." },
  { word: "about", translation: "על", example: "This book is about dogs." },
  { word: "above", translation: "מעל", example: "The picture is above the bed." },
  { word: "across", translation: "מעבר ל-", example: "Walk across the street safely." },
  { word: "action", translation: "פעולה", example: "I like action movies." },
  { word: "address", translation: "כתובת", example: "What is your home address?" },
  { word: "afraid", translation: "מפחד", example: "The little dog is afraid of loud noise." },
  { word: "after", translation: "אחרי", example: "We can play after lunch." },
  { word: "afternoon", translation: "אחר הצהריים", example: "I drink milk in the afternoon." },
  { word: "again", translation: "שוב", example: "Please say that again." },
  { word: "age", translation: "גיל", example: "What is your age?" },
  { word: "ago", translation: "לפני", example: "He left ten minutes ago." },
  { word: "agree", translation: "להסכים", example: "I agree with your idea." },
  { word: "all", translation: "כל / הכל", example: "All the students are here." },
  { word: "at all", translation: "בכלל", example: "I do not like cold food at all." },
  { word: "almost", translation: "כמעט", example: "It is almost five o\u0027clock." },
  { word: "alone", translation: "לבד", example: "She sits alone in the room." },
  { word: "alphabet", translation: "אלף-בית", example: "The English alphabet has 26 letters." },
  { word: "already", translation: "כבר", example: "I have already finished my homework." },
  { word: "also", translation: "גם", example: "He speaks English and also Hebrew." },
  { word: "always", translation: "תמיד", example: "She always drinks water with meal." },
  { word: "am", translation: "אני", example: "I am a new student here." },
  { word: "and", translation: "ו-", example: "I like apples and bananas." },
  { word: "angry", translation: "כועס", example: "Why are you angry with me?" },
  { word: "animal", translation: "חיה", example: "A cat is a small animal." },
  { word: "another", translation: "אחר", example: "Can I have another cup of tea?" },
  { word: "answer", translation: "תשובה", example: "Please give me a short answer." },
  { word: "any", translation: "כל / איזהשהו", example: "Do you have any questions?" },
  { word: "anyone", translation: "מישהו", example: "Is anyone at home?" },
  { word: "anything", translation: "משהו", example: "Do you want anything to eat?" },
  { word: "appear", translation: "להופיע", example: "A star appeared in the dark sky." },
  { word: "April", translation: "אפריל", example: "My birthday is in April." },
  { word: "are", translation: "הם / הן", example: "They are good friends." },
  { word: "arrive", translation: "להגיע", example: "What time does the bus arrive?" },
  { word: "at", translation: "ב-", example: "We met at school yesterday." },
  { word: "ask", translation: "לשאול", example: "Can I ask a question?" },
  { word: "ask for", translation: "לבקש", example: "He will ask for help." },
  { word: "at home", translation: "בבית", example: "My mother is at home today." },
  { word: "August", translation: "אוגוסט", example: "August is a hot summer month." },
  { word: "autumn", translation: "סתיו", example: "Leaves fall in autumn." },
  { word: "away", translation: "הרחק", example: "The dog ran away." },
  { word: "back", translation: "בחזרה", example: "Welcome back to class." },
  { word: "bad", translation: "רע", example: "This is a bad idea." },
  { word: "bag", translation: "תיק", example: "Put your books in your bag." },
  { word: "baby", translation: "תינוק", example: "The baby is sleeping softly." },
  { word: "be", translation: "להיות", example: "I want to be a teacher." },
  { word: "beautiful", translation: "יפה", example: "The garden has beautiful flowers." },
  { word: "because", translation: "כי", example: "I stayed home because I felt sick." },
  { word: "because of", translation: "בגלל", example: "We stopped because of the heavy rain." },
  { word: "bed", translation: "מיטה", example: "I go to bed at nine o\u0027clock." },
  { word: "before", translation: "לפני", example: "Wash your hands before eating." },
  { word: "begin", translation: "להתחיל", example: "Lesson will begin soon." },
  { word: "behind", translation: "מאחורי", example: "The cat is behind the sofa." },
  { word: "believe", translation: "להאמין", example: "I believe you are right." },
  { word: "beside", translation: "ליד", example: "Sit beside me on the bench." },
  { word: "best", translation: "הכי טוב", example: "You are my best friend." },
  { word: "better", translation: "טוב יותר", example: "I feel better today than yesterday." },
  { word: "between", translation: "בין", example: "The park is between two buildings." },
  { word: "big", translation: "גדול", example: "Elephants are big animals." },
  { word: "birthday", translation: "יום הולדת", example: "Happy birthday to you!" },
  { word: "a bit of", translation: "קצת", example: "Add a bit of sugar to the coffee." },
  { word: "black", translation: "שחור", example: "He wears a black hat." },
  { word: "blue", translation: "כחול", example: "The sky is blue today." },
  { word: "board", translation: "לוח", example: "Look at the classroom board." },
  { word: "body", translation: "גוף", example: "Exercise is good for your body." },
  { word: "book", translation: "ספר", example: "I am reading a story book." },
  { word: "bored", translation: "משועמם", example: "I am bored, let us play a game." },
  { word: "boring", translation: "משעמם", example: "This film is very boring." },
  { word: "bottle", translation: "בקבוק", example: "This bottle is full of cold water." },
  { word: "box", translation: "קופסה", example: "The toys are inside the box." },
  { word: "boy", translation: "ילד", example: "The boy plays in the park." },
  { word: "bread", translation: "לחם", example: "I eat bread for breakfast." },
  { word: "break", translation: "לשבור", example: "Do not break the glass." },
  { word: "breakfast", translation: "ארוחת בוקר", example: "We eat breakfast every morning." },
  { word: "bring", translation: "להביא", example: "Please bring your book to class." },
  { word: "brother", translation: "אח", example: "My brother is eight years old." },
  { word: "brown", translation: "חום", example: "The dog has brown fur." },
  { word: "build", translation: "לבנות", example: "They build a new house." },
  { word: "bus", translation: "אוטובוס", example: "I take the bus to school." },
  { word: "busy", translation: "עסוק", example: "My father is very busy today." },
  { word: "but", translation: "אבל", example: "I like tea, but I dislike coffee." },
  { word: "buy", translation: "לקנות", example: "I want to buy a new shirt." },
  { word: "by", translation: "על ידי", example: "We went there by car." },
  { word: "call", translation: "להתקשר", example: "Call me in the evening." },
  { word: "can", translation: "יכול", example: "I can swim fast." },
  { word: "capital", translation: "עיר בירה", example: "Jerusalem is the capital of Israel." },
  { word: "car", translation: "מכונית", example: "My dad drives a red car." },
  { word: "care", translation: "לדאוג", example: "She takes good care of her cat." },
  { word: "careful", translation: "זהיר", example: "Be careful when you use scissors." },
  { word: "cat", translation: "חתול", example: "My cat sleeps on the chair." },
  { word: "catch", translation: "לתפוס", example: "Can you catch the ball?" },
  { word: "center", translation: "מרכז", example: "The shop is in the center of town." },
  { word: "chair", translation: "כיסא", example: "Sit on this wooden chair." },
  { word: "change", translation: "לשנות", example: "You need to change your clothes." },
  { word: "cheap", translation: "זול", example: "This pen is very cheap." },
  { word: "children", translation: "ילדים", example: "The children play outside." },
  { word: "chocolate", translation: "שוקולד", example: "I like milk chocolate." },
  { word: "class", translation: "כיתה", example: "Our English class starts now." },
  { word: "classroom", translation: "חדר כיתה", example: "The classroom is clean and bright." },
  { word: "clean", translation: "נקי", example: "Your room is very clean." },
  { word: "clear", translation: "ברור", example: "The explanation was clear." },
  { word: "close", translation: "לסגור", example: "Please close the door." },
  { word: "closed", translation: "סגור", example: "The shop is closed today." },
  { word: "coffee", translation: "קפה", example: "He drinks hot coffee every morning." },
  { word: "cold", translation: "קר", example: "It is cold outside in winter." },
  { word: "color", translation: "צבע", example: "Red is my favorite color." },
  { word: "come", translation: "לבוא", example: "Come here, please." },
  { word: "come back", translation: "לחזור", example: "When will you come back home?" },
  { word: "computer", translation: "מחשב", example: "I write on my computer." },
  { word: "cool", translation: "קריר", example: "The evening air is cool." },
  { word: "copy", translation: "להעתיק", example: "Copy these words into your notebook." },
  { word: "cost", translation: "לעלות", example: "How much does this book cost?" },
  { word: "count", translation: "לספור", example: "Can you count from one to ten?" },
  { word: "country", translation: "מדינה", example: "Israel is a small country." },
  { word: "of course", translation: "כמובן", example: "Of course I will help you." },
  { word: "cross", translation: "לחצות", example: "Cross the street carefully." },
  { word: "road", translation: "כביש", example: "Look both ways before crossing the road." },
  { word: "cry", translation: "לבכות", example: "Babies cry when they are hungry." },
  { word: "cut", translation: "לחתוך", example: "Cut the bread with a knife." },
  { word: "dad", translation: "אבא", example: "My dad works at an office." },
  { word: "dark", translation: "חשוך", example: "It gets dark at night." },
  { word: "date", translation: "תאריך", example: "What is today\u0027s date?" },
  { word: "daughter", translation: "בת", example: "She is her mother\u0027s daughter." },
  { word: "day", translation: "יום", example: "Have a nice day!" },
  { word: "Dear", translation: "יקר", example: "Dear friend, how are you?" },
  { word: "December", translation: "דצמבר", example: "December is the last month of the year." },
  { word: "decide", translation: "להחליט", example: "I need to decide what to wear." },
  { word: "dictionary", translation: "מילון", example: "Use a dictionary to find the word." },
  { word: "different", translation: "שונה", example: "We have different ideas." },
  { word: "difficult", translation: "קשה", example: "This math question is difficult." },
  { word: "doctor", translation: "רופא", example: "The doctor helps sick people." },
  { word: "do", translation: "לעשות", example: "Do your best work today." },
  { word: "dog", translation: "כלב", example: "My dog likes to run." },
  { word: "don\u0027t", translation: "לא", example: "Don\u0027t touch the hot stove." },
  { word: "door", translation: "דלת", example: "Open the door for your teacher." },
  { word: "down", translation: "למטה", example: "Sit down on the chair." },
  { word: "draw", translation: "לצייר", example: "I like to draw flowers." },
  { word: "dress", translation: "שמלה", example: "She wears a pink dress." },
  { word: "drink", translation: "לשתות", example: "Drink plenty of water." },
  { word: "dry", translation: "יבש", example: "My clothes are dry now." },
  { word: "each", translation: "כל", example: "Each child has a toy." },
  { word: "early", translation: "מוקדם", example: "I get up early in the morning." },
  { word: "ears", translation: "אוזניים", example: "Rabbits have long ears." },
  { word: "easy", translation: "קל", example: "This test is easy for me." },
  { word: "eat", translation: "לאכול", example: "We eat dinner together." },
  { word: "eighteen", translation: "שמונה עשרה", example: "My cousin is eighteen years old." },
  { word: "eighty", translation: "שמונים", example: "My grandmother is eighty years old." },
  { word: "eleven", translation: "אחד עשר", example: "I have eleven apples." },
  { word: "email", translation: "דוא\"ל", example: "Send me an email today." },
  { word: "end", translation: "סוף", example: "This is the end of the book." },
  { word: "English", translation: "אנגלית", example: "We speak English in class." },
  { word: "enjoy", translation: "ליהנות", example: "I enjoy playing music." },
  { word: "enough", translation: "מספיק", example: "We have enough food for everyone." },
  { word: "enter", translation: "להיכנס", example: "Please enter the room quietly." },
  { word: "evening", translation: "ערב", example: "We eat dinner in the evening." },
  { word: "every", translation: "כל", example: "She walks every morning." },
  { word: "everybody", translation: "כולם", example: "Everybody loves a warm smile." },
  { word: "everyone", translation: "כולם", example: "Everyone is happy today." },
  { word: "everything", translation: "הכל", example: "Everything is ready for the party." },
  { word: "example", translation: "דוגמה", example: "This picture is a good example." },
  { word: "excuse me", translation: "סליחה", example: "Excuse me, where is the bus stop?" },
  { word: "exercise", translation: "תרגיל", example: "Daily exercise is good for you." },
  { word: "expensive", translation: "יקר", example: "That car is very expensive." },
  { word: "extra", translation: "נוסף", example: "Do you need an extra key?" },
  { word: "eyes", translation: "עיניים", example: "She has blue eyes." },
  { word: "face", translation: "פנים", example: "Wash your face with water." },
  { word: "fact", translation: "עובדה", example: "It is a fact that water is clear." },
  { word: "fair", translation: "הוגן", example: "The game was fun and fair." },
  { word: "fall", translation: "ליפול", example: "Leaves fall in autumn." },
  { word: "family", translation: "משפחה", example: "I love my family very much." },
  { word: "far", translation: "רחוק", example: "The beach is not far from here." },
  { word: "fast", translation: "מהר", example: "He runs very fast." },
  { word: "father", translation: "אבא", example: "My father works at a bank." },
  { word: "favorite", translation: "מועדף", example: "Blue is my favorite color." },
  { word: "February", translation: "פברואר", example: "February is a short month." },
  { word: "feel", translation: "להרגיש", example: "I feel happy today." },
  { word: "a few", translation: "כמה", example: "I have a few books to read." },
  { word: "fifteen", translation: "חמש עשרה", example: "The class starts in fifteen minutes." },
  { word: "fifth", translation: "חמישי", example: "May is the fifth month of the year." },
  { word: "fifty", translation: "חמישים", example: "My grandfather is fifty years old." },
  { word: "film", translation: "סרט", example: "We watched a funny film last night." },
  { word: "find", translation: "למצוא", example: "I cannot find my keys." },
  { word: "find out", translation: "לגלות", example: "Call me when you find out the answer." },
  { word: "fine", translation: "בסדר", example: "I am fine, thank you." },
  { word: "finish", translation: "לסיים", example: "Please finish your dinner." },
  { word: "fire", translation: "אש", example: "The fire keeps us warm." },
  { word: "first", translation: "ראשון", example: "This is my first time here." },
  { word: "five", translation: "חמש", example: "I have five pens on my desk." },
  { word: "flower", translation: "פרח", example: "This red flower smells nice." },
  { word: "fly", translation: "לעוף", example: "Birds fly in the sky." },
  { word: "food", translation: "אוכל", example: "Italian food is very tasty." },
  { word: "foot", translation: "רגל", example: "My left foot hurts." },
  { word: "feet", translation: "רגליים", example: "Put your shoes on your feet." },
  { word: "for", translation: "בשביל", example: "This gift is for you." },
  { word: "forget", translation: "לשכוח", example: "Do not forget your bag." },
  { word: "four", translation: "ארבע", example: "A cat has four legs." },
  { word: "fourteen", translation: "ארבע עשרה", example: "She is fourteen years old." },
  { word: "fourth", translation: "רביעי", example: "He lives on the fourth floor." },
  { word: "forty", translation: "ארבעים", example: "There are forty students in the hall." },
  { word: "free", translation: "חופשי", example: "Are you free this weekend?" },
  { word: "Friday", translation: "יום שישי", example: "We go home early on Friday." },
  { word: "friend", translation: "חבר", example: "Tom is my best friend." },
  { word: "from", translation: "מ", example: "She is from Canada." },
  { word: "in front of", translation: "לפני", example: "Stand in front of the line." },
  { word: "full", translation: "מלא", example: "The glass is full of milk." },
  { word: "funny", translation: "מצחיק", example: "He told a funny story." },
  { word: "game", translation: "משחק", example: "Let\u0027s play a video game." },
  { word: "garden", translation: "גינה", example: "There are red roses in the garden." },
  { word: "get", translation: "לקבל", example: "I get good marks in school." },
  { word: "girl", translation: "ילדה", example: "The girl is playing with a doll." },
  { word: "give", translation: "לתת", example: "Please give me a cup of water." },
  { word: "glad", translation: "שמח", example: "I am glad to see you." },
  { word: "glass", translation: "כוס", example: "Drink a glass of water." },
  { word: "go", translation: "ללכת", example: "I go to school by bus." },
  { word: "go on", translation: "להמשיך", example: "Please go on with your story." },
  { word: "going to", translation: "עומד ל", example: "I am going to visit my grandma." },
  { word: "good", translation: "טוב", example: "Have a good day!" },
  { word: "good at", translation: "טוב ב", example: "She is good at math." },
  { word: "goodbye", translation: "להתראות", example: "Say goodbye to your friends." },
  { word: "grade", translation: "ציון", example: "He got a high grade on the test." },
  { word: "great", translation: "נהדר", example: "We had a great time at the park." },
  { word: "green", translation: "ירוק", example: "The grass is soft and green." },
  { word: "grow", translation: "לגדול", example: "Plants need sunlight to grow." },
  { word: "guess", translation: "לנחש", example: "Can you guess what is in the box?" },
  { word: "hair", translation: "שיער", example: "She has long hair." },
  { word: "half", translation: "חצי", example: "Cut the apple in half." },
  { word: "half past", translation: "וחצי", example: "It is half past two." },
  { word: "hand", translation: "יד", example: "Hold my hand to cross the street." },
  { word: "hang", translation: "לתלות", example: "Hang your coat near the door." },
  { word: "happen", translation: "לקרות", example: "Accidents can happen anytime." },
  { word: "happy", translation: "שמח", example: "The children are happy today." },
  { word: "hard", translation: "קשה", example: "This test was very hard." },
  { word: "hat", translation: "כובע", example: "Wear a hat on sunny days." },
  { word: "have", translation: "יש", example: "I have two sisters." },
  { word: "have to", translation: "חייב", example: "I have to clean my room." },
  { word: "head", translation: "ראש", example: "Nod your head if you agree." },
  { word: "hear", translation: "לשמוע", example: "I hear music from next door." },
  { word: "hello", translation: "שלום", example: "Hello, nice to meet you." },
  { word: "help", translation: "לעזור", example: "Can you help me with this box?" },
  { word: "her", translation: "שלה", example: "I saw her at the store." },
  { word: "herself", translation: "עצמה", example: "She built the house herself." },
  { word: "here", translation: "כאן", example: "Come here and sit down." },
  { word: "high", translation: "גבוה", example: "The bird flew high into the sky." },
  { word: "him", translation: "אותו", example: "I talked to him yesterday." },
  { word: "himself", translation: "עצמו", example: "He fixed the bike himself." },
  { word: "his", translation: "שלו", example: "His cat is very cute." },
  { word: "hold", translation: "להחזיק", example: "Hold the bag for a moment." },
  { word: "home", translation: "בית", example: "I want to go home now." },
  { word: "hope", translation: "לקוות", example: "I hope it stays sunny today." },
  { word: "hot", translation: "חם", example: "The tea is very hot." },
  { word: "hour", translation: "שעה", example: "We waited for one hour." },
  { word: "house", translation: "בית", example: "They live in a small white house." },
  { word: "how", translation: "איך", example: "How are you doing today?" },
  { word: "hundred", translation: "מאה", example: "There are one hundred pages in the book." },
  { word: "hungry", translation: "רעב", example: "I am hungry, let\u0027s eat lunch." },
  { word: "idea", translation: "רעיון", example: "That is a great idea!" },
  { word: "if", translation: "אם", example: "Call me if you need anything." },
  { word: "immediately", translation: "מיד", example: "Please come here immediately." },
  { word: "important", translation: "חשוב", example: "It is important to study." },
  { word: "impossible", translation: "בלתי אפשרי", example: "Nothing is impossible if you try." },
  { word: "in", translation: "בתוך", example: "The toy is in the box." },
  { word: "inside", translation: "בפנים", example: "It is warm inside the house." },
  { word: "interested in", translation: "מעוניין ב", example: "I am interested in art." },
  { word: "interesting", translation: "מעניין", example: "This story is very interesting." },
  { word: "into", translation: "לתוך", example: "She walked into the room." },
  { word: "invite", translation: "להזמין", example: "I will invite my friends to the party." },
  { word: "is", translation: "הוא", example: "He is my brother." },
  { word: "it", translation: "זה", example: "It is a beautiful day." },
  { word: "its", translation: "שלו", example: "The dog wags its tail." },
  { word: "itself", translation: "עצמו", example: "The cat cleaned itself." },
  { word: "January", translation: "ינואר", example: "January is the first month of the year." },
  { word: "job", translation: "עבודה", example: "He likes his new job." },
  { word: "June", translation: "יוני", example: "School ends in June." },
  { word: "July", translation: "יולי", example: "July is usually hot." },
  { word: "just", translation: "רק", example: "I just want a cup of tea." },
  { word: "keep", translation: "לשמור", example: "Keep your money in a safe place." },
  { word: "kid", translation: "ילד", example: "The kid is playing in the park." },
  { word: "kind", translation: "אדיב", example: "Thank you for being so kind." },
  { word: "know", translation: "לדעת", example: "I know the answer to this question." },
  { word: "large", translation: "גדול", example: "We live in a large city." },
  { word: "last", translation: "אחרון", example: "This is the last cookie in the box." },
  { word: "late", translation: "מאוחר", example: "Do not be late for school." },
  { word: "learn", translation: "ללמוד", example: "Children learn quickly." },
  { word: "at least", translation: "לפחות", example: "Drink at least eight glasses of water." },
  { word: "leave", translation: "לעזוב", example: "We leave for school at eight." },
  { word: "left", translation: "שמאל", example: "Turn left at the corner." },
  { word: "less", translation: "פחות", example: "Eat less sugar to stay healthy." },
  { word: "lesson", translation: "שיעור", example: "The English lesson begins now." },
  { word: "let\u0027s", translation: "בואו", example: "Let\u0027s play football together." },
  { word: "letter", translation: "מכתב", example: "I received a letter from my friend." },
  { word: "lie", translation: "לשקר", example: "Never tell a lie to your friends." },
  { word: "life", translation: "חיים", example: "Life is full of wonderful surprises." },
  { word: "light", translation: "אור", example: "Turn on the light, please." },
  { word: "like", translation: "לאהוב", example: "I like ice cream." },
  { word: "listen", translation: "להקשיב", example: "Listen to the teacher." },
  { word: "little", translation: "קטן", example: "I have a little dog." },
  { word: "live", translation: "לגור", example: "I live in a big city." },
  { word: "look", translation: "להסתכל", example: "Look at the red car." },
  { word: "long", translation: "ארוך", example: "She has long hair." },
  { word: "lost", translation: "אבוד", example: "My cat is lost." },
  { word: "a lot of", translation: "הרבה", example: "There are a lot of books on the table." },
  { word: "lunch", translation: "ארוחת צהריים", example: "We eat lunch at twelve o\u0027clock." },
  { word: "make", translation: "להכין", example: "I make a cake for my birthday." },
  { word: "man", translation: "איש", example: "The man is walking to work." },
  { word: "many", translation: "הרבה", example: "I have many friends." },
  { word: "how many", translation: "כמה", example: "How many apples do you have?" },
  { word: "March", translation: "מרץ", example: "My birthday is in March." },
  { word: "matter", translation: "עניין", example: "It does not matter." },
  { word: "May", translation: "מאי", example: "May is a warm month." },
  { word: "maybe", translation: "אולי", example: "Maybe we can go to the park." },
  { word: "me", translation: "אותי", example: "She gave me a red ball." },
  { word: "mean", translation: "להתכוון", example: "What do you mean?" },
  { word: "meaning", translation: "משמעות", example: "What is the meaning of this word?" },
  { word: "meet", translation: "לפגוש", example: "Nice to meet you." },
  { word: "meeting", translation: "פגישה", example: "We have a meeting today." },
  { word: "memory", translation: "זיכרון", example: "I have a good memory." },
  { word: "message", translation: "הודעה", example: "I got a message on my phone." },
  { word: "middle", translation: "אמצע", example: "Stand in the middle of the room." },
  { word: "milk", translation: "חלב", example: "I drink milk every morning." },
  { word: "mind", translation: "מוח", example: "Keep that in mind." },
  { word: "minus", translation: "פחות", example: "Five minus two is three." },
  { word: "minute", translation: "דקה", example: "Wait one minute, please." },
  { word: "mistake", translation: "טעות", example: "It is okay to make a mistake." },
  { word: "mix", translation: "לערבב", example: "Mix the milk and eggs." },
  { word: "mom", translation: "אמא", example: "My mom makes good food." },
  { word: "moment", translation: "רגע", example: "Wait a moment, please." },
  { word: "Monday", translation: "יום שני", example: "School starts on Monday." },
  { word: "money", translation: "כסף", example: "I need money to buy fruit." },
  { word: "month", translation: "חודש", example: "This month is very cold." },
  { word: "moon", translation: "ירח", example: "The moon is bright tonight." },
  { word: "more", translation: "עוד", example: "Can I have more water, please?" },
  { word: "morning", translation: "בוקר", example: "Good morning, teacher!" },
  { word: "most", translation: "הכי", example: "This is the most fun game." },
  { word: "mother", translation: "אם", example: "My mother loves flowers." },
  { word: "mouth", translation: "פה", example: "Open your mouth, please." },
  { word: "move", translation: "לזוז", example: "Please move your chair." },
  { word: "movie", translation: "סרט", example: "We watch a movie together." },
  { word: "Mr", translation: "מר", example: "Mr. Smith is our teacher." },
  { word: "Mrs", translation: "גברת", example: "Mrs. Green lives next door." },
  { word: "Ms", translation: "גברת", example: "Ms. Brown works in the office." },
  { word: "much", translation: "הרבה", example: "Thank you very much." },
  { word: "how much", translation: "כמה", example: "How much is this book?" },
  { word: "music", translation: "מוזיקה", example: "I like to listen to music." },
  { word: "my", translation: "שלי", example: "This is my hat." },
  { word: "myself", translation: "עצמי", example: "I can do it myself." },
  { word: "name", translation: "שם", example: "My name is Tom." },
  { word: "near", translation: "קרוב", example: "The school is near my house." },
  { word: "need", translation: "צריך", example: "I need a pen." },
  { word: "neighbor", translation: "שכן", example: "My neighbor has a nice dog." },
  { word: "never", translation: "אף פעם", example: "I never go to bed late." },
  { word: "new", translation: "חדש", example: "I have a new bag." },
  { word: "news", translation: "חדשות", example: "My dad watches the news." },
  { word: "next", translation: "הבא", example: "See you next week." },
  { word: "next to", translation: "ליד", example: "Sit next to me." },
  { word: "nice", translation: "נחמד", example: "He is a very nice person." },
  { word: "night", translation: "לילה", example: "Good night, see you tomorrow." },
  { word: "nine", translation: "תשע", example: "I have nine pencils." },
  { word: "nineteen", translation: "תשע-עשרה", example: "He is nineteen years old." },
  { word: "ninety", translation: "תשעים", example: "My grandfather is ninety years old." },
  { word: "no", translation: "לא", example: "No, I do not want milk." },
  { word: "nobody", translation: "אף אחד", example: "Nobody is in the classroom." },
  { word: "no-one", translation: "אף אחד", example: "No-one came to the park today." },
  { word: "not", translation: "לא", example: "This is not my coat." },
  { word: "notebook", translation: "מחברת", example: "Write your name in the notebook." },
  { word: "nothing", translation: "שום דבר", example: "There is nothing in the box." },
  { word: "November", translation: "נובמבר", example: "November is a cool month." },
  { word: "now", translation: "עכשיו", example: "We are reading a book now." },
  { word: "number", translation: "מספר", example: "What is your phone number?" },
  { word: "October", translation: "אוקטובר", example: "October is my favorite month." },
  { word: "of", translation: "של", example: "This is a cup of tea." },
  { word: "often", translation: "לעיתים קרובות", example: "I often read before bed." },
  { word: "okay", translation: "בסדר", example: "Everything is okay." },
  { word: "old", translation: "ישן", example: "This is an old house." },
  { word: "on", translation: "על", example: "The book is on the table." },
  { word: "once", translation: "פעם אחת", example: "I visited London once." },
  { word: "once upon a time", translation: "היה פעם", example: "Once upon a time, there was a king." },
  { word: "one", translation: "אחד", example: "I have one sister." },
  { word: "only", translation: "רק", example: "I have only one dollar." },
  { word: "open", translation: "לפתוח", example: "Please open the window." },
  { word: "or", translation: "או", example: "Do you want tea or coffee?" },
  { word: "other", translation: "אחר", example: "Where is the other shoe?" },
  { word: "our", translation: "שלנו", example: "This is our house." },
  { word: "ourselves", translation: "עצמנו", example: "We can clean the room ourselves." },
  { word: "out", translation: "בחוץ", example: "The cat ran out." },
  { word: "over", translation: "מעל", example: "The bird flew over the tree." },
  { word: "own", translation: "של עצמו", example: "I have my own room." },
  { word: "parents", translation: "הורים", example: "My parents love me." },
  { word: "page", translation: "עמוד", example: "Turn to page five." },
  { word: "paper", translation: "נייר", example: "I need a piece of paper." },
  { word: "part", translation: "חלק", example: "This is part of the game." },
  { word: "past", translation: "עבר", example: "It is ten past five." },
  { word: "pay", translation: "לשלם", example: "I need to pay for the apple." },
  { word: "pen", translation: "עט", example: "Can I borrow your pen?" },
  { word: "pencil", translation: "עיפרון", example: "Draw a sun with your pencil." },
  { word: "people", translation: "אנשים", example: "Many people are in the park." },
  { word: "perhaps", translation: "אולי", example: "Perhaps it will rain today." },
  { word: "person", translation: "אדם", example: "She is a kind person." },
  { word: "pick up", translation: "להרים", example: "Pick up your toys, please." },
  { word: "picture", translation: "תמונה", example: "Look at this nice picture." },
  { word: "a piece of", translation: "חתיכה של", example: "Can I have a piece of cake?" },
  { word: "place", translation: "מקום", example: "This is a good place to play." },
  { word: "plan", translation: "תוכנית", example: "We have a plan for today." },
  { word: "play", translation: "לשחק", example: "Children love to play games." },
  { word: "please", translation: "בבקשה", example: "Sit down, please." },
  { word: "poor", translation: "עני", example: "The poor dog was hungry." },
  { word: "possible", translation: "אפשרי", example: "Is it possible to go now?" },
  { word: "practice", translation: "לתרגל", example: "I practice English every day." },
  { word: "problem", translation: "בעיה", example: "No problem, I can help you." },
  { word: "project", translation: "פרויקט", example: "We have a fun school project." },
  { word: "pupil", translation: "תלמיד", example: "The pupil sits at his desk." },
  { word: "push", translation: "לדחוף", example: "Push the door to open it." },
  { word: "put", translation: "לשים", example: "Put the book on the table." },
  { word: "question", translation: "שאלה", example: "I have a question for you." },
  { word: "quick", translation: "מהיר", example: "He is a very quick runner." },
  { word: "quiet", translation: "שקט", example: "Please be quiet in the library." },
  { word: "radio", translation: "רדיו", example: "We listen to music on the radio." },
  { word: "read", translation: "לקרוא", example: "I read a book every night." },
  { word: "ready", translation: "מוכן", example: "Are you ready to go?" },
  { word: "real", translation: "אמיתי", example: "Is that a real dog?" },
  { word: "really", translation: "באמת", example: "I really like ice cream." },
  { word: "red", translation: "אדום", example: "The apple is red." },
  { word: "remember", translation: "לזכור", example: "I remember your name." },
  { word: "rest", translation: "לנוח", example: "I need to rest now." },
  { word: "return", translation: "לחזור", example: "When will you return home?" },
  { word: "rich", translation: "עשיר", example: "The king is very rich." },
  { word: "right", translation: "נכון", example: "Your answer is right." },
  { word: "room", translation: "חדר", example: "My room is big and clean." },
  { word: "round", translation: "עגול", example: "The ball is round." },
  { word: "rule", translation: "חוק", example: "Follow the classroom rule." },
  { word: "run", translation: "לרוץ", example: "Dogs like to run in the park." },
  { word: "sad", translation: "עצוב", example: "Why are you sad today?" },
  { word: "the same as", translation: "אותו דבר כמו", example: "My shoes are the same as yours." },
  { word: "Saturday", translation: "יום שבת", example: "We go to the park on Saturday." },
  { word: "say", translation: "לומר", example: "What did you say?" },
  { word: "school", translation: "בית ספר", example: "I go to school every day." },
  { word: "second", translation: "שנייה", example: "Wait one second, please." },
  { word: "see", translation: "לראות", example: "I see a blue bird." },
  { word: "send", translation: "לשלוח", example: "Send a letter to your friend." },
  { word: "sentence", translation: "משפט", example: "Write one sentence in English." },
  { word: "September", translation: "ספטמבר", example: "School begins in September." },
  { word: "seven", translation: "שבע", example: "There are seven days in a week." },
  { word: "seventeen", translation: "שבע-עשרה", example: "She is seventeen years old." },
  { word: "seventy", translation: "שבעים", example: "The book has seventy pages." },
  { word: "she", translation: "היא", example: "She is my best friend." },
  { word: "short", translation: "קצר", example: "The story is very short." },
  { word: "shout", translation: "לצעוק", example: "Do not shout in class." },
  { word: "show", translation: "להראות", example: "Can you show me your drawing?" },
  { word: "shut", translation: "לסגור", example: "Please shut the door." },
  { word: "sick", translation: "חולה", example: "He is sick today." },
  { word: "side", translation: "צד", example: "Sit on this side of the table." },
  { word: "sign", translation: "שלט", example: "Look at the red sign." },
  { word: "simple", translation: "פשוט", example: "This question is very simple." },
  { word: "sing", translation: "לשיר", example: "She likes to sing songs." },
  { word: "sister", translation: "אחות", example: "My sister is nine years old." },
  { word: "sit", translation: "לשבת", example: "Please sit on the chair." },
  { word: "six", translation: "שש", example: "I have six pencils." },
  { word: "sixteen", translation: "שש עשרה", example: "He is sixteen years old." },
  { word: "sixty", translation: "שישים", example: "My grandfather is sixty." },
  { word: "size", translation: "מידה", example: "What size is this shirt?" },
  { word: "sky", translation: "שמיים", example: "The sky is blue today." },
  { word: "sleep", translation: "לישון", example: "I sleep eight hours every night." },
  { word: "special", translation: "מיוחד", example: "Today is a special day." },
  { word: "spring", translation: "אביב", example: "Flowers bloom in the spring." },
  { word: "summer", translation: "קיץ", example: "Summer is warm and sunny." },
  { word: "slow", translation: "איטי", example: "The turtle is slow." },
  { word: "small", translation: "קטן", example: "They live in a small house." },
  { word: "smart", translation: "חכם", example: "She is a smart girl." },
  { word: "smile", translation: "לחייך", example: "He has a happy smile." },
  { word: "so", translation: "כל כך", example: "I am so happy to see you." },
  { word: "some", translation: "כמה", example: "I want some water, please." },
  { word: "somebody", translation: "מישהו", example: "Somebody is at the door." },
  { word: "something", translation: "משהו", example: "I need something to drink." },
  { word: "sometimes", translation: "לפעמים", example: "Sometimes I walk to school." },
  { word: "son", translation: "בן", example: "He plays football with his son." },
  { word: "soon", translation: "בקרוב", example: "The train will arrive soon." },
  { word: "song", translation: "שיר", example: "Listen to this nice song." },
  { word: "sorry", translation: "מצטער", example: "I am sorry I am late." },
  { word: "speak", translation: "לדבר", example: "I speak English and Hebrew." },
  { word: "spell", translation: "לאיית", example: "Can you spell your name?" },
  { word: "sport", translation: "ספורט", example: "Basketball is my favorite sport." },
  { word: "start", translation: "להתחיל", example: "We start school at eight o\u0027clock." },
  { word: "still", translation: "עדיין", example: "He is still sleeping." },
  { word: "story", translation: "סיפור", example: "Read me a bedtime story." },
  { word: "straight", translation: "ישר", example: "Go straight down this street." },
  { word: "strong", translation: "חזק", example: "He is very strong." },
  { word: "student", translation: "תלמיד", example: "I am a good student." },
  { word: "suddenly", translation: "פתאום", example: "Suddenly, it started to rain." },
  { word: "sun", translation: "שמש", example: "The sun is shining brightly." },
  { word: "Sunday", translation: "יום ראשון", example: "We go to school on Sunday." },
  { word: "supper", translation: "ארוחת ערב", example: "We eat supper at seven." },
  { word: "sure", translation: "בטוח", example: "Are you sure about the answer?" },
  { word: "take", translation: "לקחת", example: "Take your bag with you." },
  { word: "talk", translation: "לדבר", example: "We talk on the phone every day." },
  { word: "tall", translation: "גבוה", example: "My brother is tall." },
  { word: "tea", translation: "תה", example: "She drinks hot tea in the winter." },
  { word: "teach", translation: "ללמד", example: "Our teacher will teach us math." },
  { word: "telephone", translation: "טלפון", example: "The telephone is ringing." },
  { word: "television", translation: "טלוויזיה", example: "We watch television after dinner." },
  { word: "tell", translation: "לספר", example: "Tell me your secret." },
  { word: "test", translation: "מבחן", example: "We have an English test today." },
  { word: "than", translation: "מאשר", example: "A dog is bigger than a cat." },
  { word: "thank you", translation: "תודה", example: "Thank you for the present." },
  { word: "thanks", translation: "תודה", example: "Thanks for your help." },
  { word: "that", translation: "ההוא", example: "I like that red car." },
  { word: "the", translation: "ה", example: "The dog is in the garden." },
  { word: "their", translation: "שלהם", example: "This is their new house." },
  { word: "them", translation: "אותם", example: "I saw them at the park." },
  { word: "themselves", translation: "עצמם", example: "They fixed the bike by themselves." },
  { word: "then", translation: "אז", example: "Eat dinner, then wash your hands." },
  { word: "there", translation: "שם", example: "The book is over there." },
  { word: "these", translation: "אלה", example: "These shoes fit me well." },
  { word: "they", translation: "הם", example: "They are playing football." },
  { word: "thing", translation: "דבר", example: "What is that thing on the table?" },
  { word: "think", translation: "לחשוב", example: "I think you are right." },
  { word: "third", translation: "שלישי", example: "He won third place in the race." },
  { word: "thirteen", translation: "שלוש עשרה", example: "There are thirteen kids in the room." },
  { word: "thirty", translation: "שלושים", example: "My mom is thirty years old." },
  { word: "this", translation: "זה", example: "This is my favorite book." },
  { word: "those", translation: "ההם", example: "Look at those birds in the tree." },
  { word: "three", translation: "שלוש", example: "I have three apples." },
  { word: "Thursday", translation: "יום חמישי", example: "We play games on Thursday." },
  { word: "time", translation: "זמן", example: "What time is it now?" },
  { word: "today", translation: "היום", example: "Today is Monday." },
  { word: "together", translation: "יחד", example: "We like to play together." },
  { word: "tomorrow", translation: "מחר", example: "I will see you tomorrow." },
  { word: "tonight", translation: "הלילה", example: "We will watch a movie tonight." },
  { word: "too", translation: "גם", example: "I want to go to the park too." },
  { word: "too much", translation: "יותר מדי", example: "Do not eat too much candy." },
  { word: "town", translation: "עיר", example: "They live in a small town." },
  { word: "tree", translation: "עץ", example: "The bird is sitting in the tree." },
  { word: "trip", translation: "טיול", example: "We went on a fun trip." },
  { word: "truck", translation: "משאית", example: "The big truck is driving fast." },
  { word: "true", translation: "נכון", example: "That story is true." },
  { word: "try", translation: "לנסות", example: "Try to open the door." },
  { word: "Tuesday", translation: "יום שלישי", example: "We have art class on Tuesday." },
  { word: "turn", translation: "לפנות", example: "Turn right at the corner." },
  { word: "twenty", translation: "עשרים", example: "There are twenty students in class." },
  { word: "two", translation: "שתים", example: "I have two hands." },
  { word: "under", translation: "מתחת", example: "The cat is sleeping under the table." },
  { word: "understand", translation: "להבין", example: "Do you understand the lesson?" },
  { word: "until", translation: "עד", example: "Wait here until I come back." },
  { word: "up", translation: "למעלה", example: "Look up at the sky." },
  { word: "us", translation: "אותנו", example: "He came with us to the park." },
  { word: "use", translation: "להשתמש", example: "Can I use your pen?" },
  { word: "usually", translation: "בדרך כלל", example: "I usually wake up at seven." },
  { word: "vacation", translation: "חופשה", example: "We go on vacation in July." },
  { word: "very", translation: "מאוד", example: "This soup is very hot." },
  { word: "wait", translation: "לחכות", example: "Please wait for me here." },
  { word: "walk", translation: "ללכת", example: "I walk to school every morning." },
  { word: "wall", translation: "קיר", example: "There is a picture on the wall." },
  { word: "want", translation: "לרצות", example: "I want a glass of milk." },
  { word: "was", translation: "היה", example: "He was at home yesterday." },
  { word: "were", translation: "היו", example: "They were very happy." },
  { word: "wash", translation: "לשטוף", example: "Wash your hands before eating." },
  { word: "watch", translation: "לצפות", example: "We watch TV in the evening." },
  { word: "water", translation: "מים", example: "Drink a glass of water." },
  { word: "way", translation: "דרך", example: "Which way is the school?" },
  { word: "we", translation: "אנחנו", example: "We are good friends." },
  { word: "wear", translation: "ללבוש", example: "I wear a coat when it is cold." },
  { word: "Wednesday", translation: "יום רביעי", example: "See you on Wednesday." },
  { word: "week", translation: "שבוע", example: "There are seven days in a week." },
  { word: "welcome", translation: "ברוך הבא", example: "Welcome to our school!" },
  { word: "well", translation: "טוב", example: "She sings very well." },
  { word: "as well", translation: "גם כן", example: "He came to the party as well." },
  { word: "as well as", translation: "כמו גם", example: "She plays tennis as well as basketball." },
  { word: "what", translation: "מה", example: "What is your name?" },
  { word: "when", translation: "מתי", example: "When does the bus arrive?" },
  { word: "where", translation: "איפה", example: "Where is my red hat?" },
  { word: "while", translation: "בזמן ש", example: "Listen to music while you clean." },
  { word: "white", translation: "לבן", example: "The cat has soft white fur." },
  { word: "who", translation: "מי", example: "Who is that boy?" },
  { word: "why", translation: "למה", example: "Why are you laughing?" },
  { word: "will", translation: "יעשה", example: "I will call you tomorrow." },
  { word: "window", translation: "חלון", example: "Open the window, please." },
  { word: "winter", translation: "חורף", example: "It rains a lot in winter." },
  { word: "wish", translation: "משאלה", example: "Make a wish on your birthday." },
  { word: "with", translation: "עם", example: "Come to the store with me." },
  { word: "without", translation: "בלי", example: "He left without his umbrella." },
  { word: "woman", translation: "אישה", example: "That woman is my teacher." },
  { word: "wonderful", translation: "נפלא", example: "We had a wonderful day at the zoo." },
  { word: "word", translation: "מילה", example: "Learn a new English word every day." },
  { word: "work", translation: "לעבוד", example: "My mother works at a hospital." },
  { word: "world", translation: "עולם", example: "There are many countries in the world." },
  { word: "worse", translation: "גרוע יותר", example: "The rain is worse today." },
  { word: "worst", translation: "הכי גרוע", example: "That was the worst movie ever." },
  { word: "write", translation: "לכתוב", example: "Write your name on the paper." },
  { word: "wrong", translation: "שגוי", example: "That answer is wrong." },
  { word: "year", translation: "שנה", example: "Happy New Year!" },
  { word: "yellow", translation: "צהוב", example: "The sun is yellow." },
  { word: "yes", translation: "כן", example: "Yes, I would like an apple." },
  { word: "yesterday", translation: "אתמול", example: "I visited my grandma yesterday." },
  { word: "you", translation: "אתה", example: "How are you today?" },
  { word: "young", translation: "צעיר", example: "The young puppy plays all day." },
  { word: "your", translation: "שלך", example: "Where is your bag?" },
  { word: "drive", translation: "לנהוג", example: "He drives to work every day." }
  ],
  idioms: [
    { word: "break the ice", translation: "לשבור את הקרח", example: "The host told a lighthearted joke at the beginning of the seminar to break the ice among the international participants." },
    { word: "piece of cake", translation: "עניין של מה בכך", example: "Given her extensive background in software engineering, passing the entry-level coding exam was a piece of cake." },
    { word: "under the weather", translation: "לא להרגיש טוב", example: "Although she was feeling slightly under the weather, she managed to deliver her presentation seamlessly." },
    { word: "hit the books", translation: "לשקוד על הלימודים", example: "With final exams approaching next week, the medical students had no choice but to hit the books immediately." },
    { word: "once in a blue moon", translation: "לעיתים רחוקות מאוד", example: "Living abroad means he only gets to visit his hometown once in a blue moon." },
    { word: "cost an arm and a leg", translation: "לעלות הון תועפות", example: "Renovating the historic property according to modern safety standards cost an arm and a leg." },
    { word: "let the cat out of the bag", translation: "לגלות את הסוד", example: "We were planning a surprise anniversary party, but her younger brother inadvertently let the cat out of the bag." },
    { word: "on the same page", translation: "להיות באותו ראש", example: "Before proceeding with the acquisition, the board members needed to ensure they were all on the same page." },
    { word: "spill the beans", translation: "לגלות סוד", example: "Despite intense pressure during the interview, the former executive refused to spill the beans about the confidential project." },
    { word: "the ball is in your court", translation: "הכדור בידיים שלך", example: "I have submitted all the required documentation, so now the ball is in their court." },
    { word: "bite the bullet", translation: "לבלוע את הגלולה המרה", example: "Realizing that the outdated system was costing the company money, the director decided to bite the bullet and fund a complete overhaul." },
    { word: "actions speak louder than words", translation: "מעשים מדברים חזק יותר ממילים", example: "He promised to improve his punctuality, but actions speak louder than words." },
    { word: "better late than never", translation: "מוטב מאוחר מאשר לעולם לא", example: "She finally submitted her research paper two days after the deadline, believing it was better late than never." },
    { word: "get out of hand", translation: "לצאת מכלל שליטה", example: "Security was called when the protest began to get out of hand near the parliament building." },
    { word: "hit the nail on the head", translation: "לפגוע בול", example: "Her analysis of the market trends hit the nail on the head, accurately predicting the upcoming recession." },
    { word: "kill two birds with one stone", translation: "להרוג שתי ציפורים במכה אחת", example: "By attending the conference in Berlin, he managed to network with potential clients and visit his family, killing two birds with one stone." },
    { word: "miss the boat", translation: "להחמיץ את ההזדמנות", example: "Investors who hesitated to buy tech stocks early last year completely missed the boat." },
    { word: "pull yourself together", translation: "להתעשת", example: "Despite the unexpected crisis, the team manager had to pull himself together and make a rational decision." },
    { word: "see eye to eye", translation: "לראות עין בעין", example: "Although they are close friends, they rarely see eye to eye when it comes to political matters." },
    { word: "speak of the devil", translation: "מדברים על החמור", example: "We were just discussing how much Sarah enjoyed her trip, and speak of the devil, she walked into the room." },
    { word: "take it with a grain of salt", translation: "לקחת בעירבון מוגבל", example: "Given the source\u0027s bias, you should take those rumors with a grain of salt." },
    { word: "the best of both worlds", translation: "ליהנות מכל העולמות", example: "Working remotely from a countryside home allows her to enjoy the best of both worlds: a rewarding career and a peaceful lifestyle." },
    { word: "time flies", translation: "הזמן טס", example: "It is hard to believe we graduated five years ago; time flies when you are pursuing your goals." },
    { word: "when pigs fly", translation: "כשחזירים יעופו", example: "He claims he will start going to the gym every morning, but considering his sleeping habits, that will happen when pigs fly." },
    { word: "a blessing in disguise", translation: "ברכה בתחפושת", example: "Losing that job felt devastating at first, but it turned out to be a blessing in disguise when it led her to start her own successful business." }  ],
  phrasalVerbs: [
    { word: "give up", translation: "לוותר", example: "Despite numerous setbacks during the experiment, the research team refused to give up." },
    { word: "look forward to", translation: "לצפות ל...", example: "The regional directors are looking forward to reviewing the annual performance reports next month." },
    { word: "find out", translation: "לגלות", example: "Investigators are working tirelessly to find out the root cause of the system failure." },
    { word: "get along with", translation: "להסתדר עם", example: "A successful project manager must be able to get along with colleagues from diverse backgrounds." },
    { word: "break down", translation: "להתפרק", example: "If the negotiations break down, both parties risk losing millions in potential revenue." },
    { word: "bring up", translation: "להעלות נושא", example: "During the strategy session, she decided to bring up the issue of employee burnout." },
    { word: "call off", translation: "לבטל", example: "Due to severe weather conditions, the organizers had to call off the outdoor festival." },
    { word: "carry on", translation: "להמשיך", example: "Despite the noisy background, the speaker managed to carry on with her lecture." },
    { word: "come across", translation: "להיתקל ב...", example: "While researching in the national archives, the historian came across a rare 18th-century manuscript." },
    { word: "cut down on", translation: "לצמצם", example: "To meet their sustainability goals, the corporation plans to cut down on single-use plastics across all offices." },
    { word: "deal with", translation: "ללמוד להתמודד עם", example: "The customer service department had to deal with an influx of inquiries following the software update." },
    { word: "drop by", translation: "לקפוץ לביקור", example: "Feel free to drop by my office tomorrow afternoon if you need clarification on the assignment." },
    { word: "end up", translation: "לסיים ב...", example: "If you don\u0027t stick to your budget, you might end up spending all your savings on non-essential items." },
    { word: "figure out", translation: "לפענח", example: "It took the engineers several days to figure out how to bypass the security flaw." },
    { word: "get away with", translation: "לחמוק מעונש", example: "The corrupt official thought he could get away with embezzling funds, but an internal audit exposed him." },
    { word: "get over", translation: "להתגבר על", example: "It took her several months to get over the disappointment of not getting the promotion." },
    { word: "go through", translation: "לעבור תהליך", example: "The company is currently going through a major restructuring process to improve efficiency." },
    { word: "hang out", translation: "לבלות", example: "In their spare time, the researchers like to hang out at a local coffee shop to discuss non-work topics." },
    { word: "hold on", translation: "להמתין", example: "Please hold on for a moment while I transfer your call to the department head." },
    { word: "keep up with", translation: "לעמוד בקצב של", example: "With technology evolving so rapidly, professionals must continuously learn to keep up with industry standards." },
    { word: "look after", translation: "לטפל ב...", example: "She took a sabbatical year to look after her elderly parents." },
    { word: "make up", translation: "להמציא", example: "He attempted to make up an elaborate excuse for his absence, but no one believed him." },
    { word: "put off", translation: "לדחות", example: "You shouldn\u0027t put off scheduling your annual health checkup simply because you are busy." },
    { word: "run into", translation: "להיתקל ב...", example: "I was surprised to run into my former university professor while attending an international conference in Chicago." },
    { word: "set up", translation: "להקים", example: "The non-profit organization was set up to provide educational resources to underprivileged communities." }  ],
  advancedVocab: [
    { word: "achieve", translation: "להשיג", example: "Through dedication and strategic planning, the company managed to achieve record sales this fiscal year." },
    { word: "accomplish", translation: "להשלים בהצלחה", example: "It is remarkable how much the small team was able to accomplish within such a tight deadline." },
    { word: "ambitious", translation: "שאפתני", example: "The city unveiled an ambitious plan to achieve carbon neutrality within the next decade." },
    { word: "beneficial", translation: "מועיל", example: "Establishing regular communication channels proved beneficial for long-term collaboration." },
    { word: "challenging", translation: "מאתגר", example: "Navigating the complex regulatory framework presented a challenging obstacle for the startup." },
    { word: "collaborate", translation: "לשתף פעולה", example: "Scientists from multiple disciplines were asked to collaborate on developing sustainable energy solutions." },
    { word: "consequence", translation: "תוצאה", example: "Failing to address climate change in a timely manner will have severe economic consequences." },
    { word: "considerable", translation: "ניכר", example: "The research team devoted a considerable amount of time to verifying the statistical accuracy of the data." },
    { word: "contribute", translation: "לתרום", example: "Every employee is encouraged to contribute innovative ideas to the company\u0027s weekly brainstorming sessions." },
    { word: "convince", translation: "לשכנע", example: "The persuasive presentation failed to convince the investors to provide additional funding." },
    { word: "curious", translation: "סקרן", example: "Her curious nature constantly drives her to explore new fields of study outside her comfort zone." },
    { word: "determine", translation: "לקבוע", example: "The findings of the investigation will determine whether further safety measures need to be implemented." },
    { word: "efficient", translation: "יעיל", example: "Adopting automated workflow tools enabled the team to become significantly more efficient." },
    { word: "enormous", translation: "עצום", example: "The construction of the new transportation hub required an enormous financial investment." },
    { word: "essential", translation: "חיוני", example: "Developing strong critical thinking skills is essential for academic success in higher education." },
    { word: "establish", translation: "לבסס", example: "The university hopes to establish a research center dedicated to renewable energy technologies." },
    { word: "evaluate", translation: "להעריך", example: "The panel of experts was appointed to evaluate the feasibility of the proposed urban development project." },
    { word: "exhausted", translation: "תשוש", example: "After working a seventy-hour work week, the medical staff was visibly exhausted." },
    { word: "fascinating", translation: "מרתק", example: "The documentary offered a fascinating glimpse into the social structure of deep-sea marine life." },
    { word: "flexible", translation: "גמיש", example: "Modern organizations require flexible employees who can easily adapt to changing market conditions." },
    { word: "frustrated", translation: "מתוסכל", example: "The software developers grew frustrated after encountering repeated bugs during the testing phase." },
    { word: "generous", translation: "נדיב", example: "The university received a generous donation from an anonymous benefactor to expand its library." },
    { word: "genuine", translation: "אמיתי", example: "His genuine interest in the welfare of his colleagues made him a highly respected manager." },
    { word: "gradually", translation: "בהדרגה", example: "As economic stability returned, public confidence in the banking sector gradually increased." },
    { word: "guarantee", translation: "להבטיח", example: "The manufacturer offers a five-year warranty to guarantee the reliability of its product." },
    { word: "inevitable", translation: "בלתי נמנע", example: "In any rapidly expanding company, experiencing organizational growing pains is almost inevitable." },
    { word: "influence", translation: "להשפיע", example: "Cultural factors can significantly influence consumer behavior in global markets." },
    { word: "inspire", translation: "לעורר השראה", example: "The CEO\u0027s passion and visionary leadership served to inspire employees across all departments." },
    { word: "maintain", translation: "לתחזק", example: "To maintain high quality standards, the factory conducts rigorous daily inspections of all machinery." },
    { word: "motivate", translation: "להניע", example: "Offering performance-based bonuses is an effective strategy to motivate sales staff." }  ]
};

// Hebrew display labels for each category key.
const CATEGORY_LABELS = {
  basics: "בסיס",
  food: "אוכל",
  travel: "טיולים",
  business: "עסקים",
  foundation: "אוצר מילים - Band I",
  idioms: "ניבים",
  phrasalVerbs: "פעלים דו-מיליים",
  advancedVocab: "אוצר מילים מתקדם"
};

// Which categories are beginner vs. advanced level (used for game badging
// and to restrict advanced-only games to appropriate content).
const CATEGORY_LEVELS = {
  basics: "beginner",
  food: "beginner",
  travel: "beginner",
  business: "beginner",
  foundation: "beginner",
  idioms: "advanced",
  phrasalVerbs: "advanced",
  advancedVocab: "advanced"
};

// Explicit window exposure so module scripts (which only reliably see
// globals via `window`, not classic-script `const` bindings) can use this
// as offline/fallback data - see words-db.js.
window.WORD_DATA = WORD_DATA;
window.CATEGORY_LABELS = CATEGORY_LABELS;
window.CATEGORY_LEVELS = CATEGORY_LEVELS;
