/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from "@trpc/server";
import { z } from "zod";

const t = initTRPC.create();
const publicProcedure = t.procedure;
import { registerInputSchema, authOutputSchema, loginInputSchema, authUserOutputSchema } from "../auth/dto/auth.dto.js";
import { courseItemListOutputSchema, addCourseItemInputSchema, courseItemOutputSchema, removeCourseItemInputSchema } from "../course-content/dto/course-content.dto.js";
import { feedbackListOutputSchema, createFeedbackInputSchema, removeFeedbackInputSchema } from "../feedback/dto/feedback.dto.js";
import { userStatsOutputSchema, recordAnswerInputSchema, statsWithUnlocksOutputSchema, recordGameCompletedInputSchema, savePlacementResultInputSchema } from "../user-stats/dto/user-stats.dto.js";
import { listWordsByCategoryInputSchema, wordListOutputSchema } from "../words/dto/word.dto.js";
import type { CourseContentRouter } from "../course-content/course-content.router.js";
import type { FeedbackRouter } from "../feedback/feedback.router.js";

const appRouter = t.router({
  auth: t.router({
    register: publicProcedure
      .input(registerInputSchema)
      .output(authOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    login: publicProcedure
      .input(loginInputSchema)
      .output(authOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    me: publicProcedure
      .output(authUserOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  courseContent: t.router({
    list: publicProcedure
      .output(courseItemListOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    add: publicProcedure
      .input(addCourseItemInputSchema)
      .output(courseItemOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    remove: publicProcedure
      .input(removeCourseItemInputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as unknown as Awaited<ReturnType<CourseContentRouter["remove"]>>)
    }),
  feedback: t.router({
    list: publicProcedure
      .output(feedbackListOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    create: publicProcedure
      .input(createFeedbackInputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as unknown as Awaited<ReturnType<FeedbackRouter["create"]>>),
    remove: publicProcedure
      .input(removeFeedbackInputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as unknown as Awaited<ReturnType<FeedbackRouter["remove"]>>)
    }),
  userStats: t.router({
    getStats: publicProcedure
      .output(userStatsOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    recordAnswer: publicProcedure
      .input(recordAnswerInputSchema)
      .output(statsWithUnlocksOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    recordGameCompleted: publicProcedure
      .input(recordGameCompletedInputSchema)
      .output(statsWithUnlocksOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any),
    savePlacementResult: publicProcedure
      .input(savePlacementResultInputSchema)
      .output(userStatsOutputSchema)
      .mutation(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    }),
  words: t.router({
    listByCategory: publicProcedure
      .input(listWordsByCategoryInputSchema)
      .output(wordListOutputSchema)
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as any)
    })
});

export type AppRouter = typeof appRouter;
